wildfly:
 rules:
   - title: "test"
   - body: "test"
     notify: [Dkafetzis]
 format:
   title-check:
     pattern: "\\[WFLY-\\d+\\]\\s+.*|WFLY-\\d+\\s+.*"
     message: "Wrong content of the title!"
   description:
     pattern: "JIRA:\\s+https://issues.jboss.org/browse/WFLY-\\d+|https://issues.jboss.org/browse/WFLY-\\d+"
     message: "The PR description must contain a link to the JIRA issue"
   commits-quantity:
     quantity: "1-3"
     message: "Too many commits in PR!"
   commits-message:
     pattern: "\\[WFLY-\\d+\\]\\s+.*|WFLY-\\d+\\s+.*"
     message: "One of the messages is incorrect"
   base-branch:
     pattern: "main"
     message: "You are pushing to the wrong branch!"
